[build]
  command = "npx prisma generate && next build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  PRISMA_SKIP_GENERATE_AND_VALIDATE = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"
